name: Integration Tests

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: use cache if package-lock has not changed
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm run test:integration
        env:
          INTEGRATION_TEST_API_API_KEY: ${{secrets.INTEGRATION_TEST_API_API_KEY}}
          INTEGRATION_TEST_API_NAVIGATION_SERVICE: ${{secrets.INTEGRATION_TEST_API_NAVIGATION_SERVICE}}
          INTEGRATION_TEST_API_CAAS: ${{secrets.INTEGRATION_TEST_API_CAAS}}
          INTEGRATION_TEST_API_PROJECT_ID: ${{secrets.INTEGRATION_TEST_API_PROJECT_ID}}
          INTEGRATION_TEST_API_TENANT_ID: ${{secrets.INTEGRATION_TEST_API_TENANT_ID}}
